import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";

export default function Home({results}) {
  
  console.log(results)
  const fetchData = async () => {
    const response = await fetch("https://api.themoviedb.org/3/trending/all/week?api_key=f298792b7aa62ed73f1c0e219bfc90b5&language=en-US");
    const data = await response.json()
    console.log(data.results)
  }

  return (
    <div>
      
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />

      <Results results = {results} />
    </div>
  );
} 

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  console.log(genre)
  const response = await fetch(
    `https://api.themoviedb.org/3${requests[genre]?.url || requests.fecthTrending.url}`
  )
  const data = await response.json();
  
  return {
    props: {
      results: data.results
    }
  }
}
